apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
  namespace: kongroo
  labels:
    app.kubernetes.io/name: identity-api
    app.kubernetes.io/instance: identity-api
    app.kubernetes.io/version: "0.0.5"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: kongroo
    app.kubernetes.io/managed-by: kubectl
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jwt__Issuer: "Kongroo.Identity.Api"
  Jwt__Audience: "Kongroo.Identity.Api"
  Jwt__AccessTokenLifetimeMinutes: "15"
  OutboxProcessing__PollingInterval: "00:00:05"
  OutboxProcessing__BatchSize: "20"
  BootstrapAdmin__Username: "admin"
  BootstrapAdmin__Email: "admin@kongroo.dev"
  BootstrapAdmin__Name: "Administrator"
  RabbitMq__Host: "rabbitmq"
