apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: kongroo
  labels:
    app.kubernetes.io/name: identity-api
    app.kubernetes.io/instance: identity-api
    app.kubernetes.io/version: "0.0.5"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: kongroo
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    app: identity-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
